import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { storage } from '../config/client';
import { ref,getDownloadURL } from 'firebase/storage';
import { useEffect } from 'react';


export default function Home() {

  const pathReference = ref(storage, 'images/badges/FACEA.png');
  const testImage =() =>{
      getDownloadURL(pathReference)
    .then((url) => {
      // `url` is the download URL for 'images/stars.jpg'

      // Or inserted into an <img> element
      const img = document.getElementById('badge');
      console.log(url)
      img.setAttribute('src', url);
    })
    .catch((error) => {
      // Handle any errors
    });
  }
  useEffect(() => {
    testImage()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Qr - Code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Pasaporte Virtual
        </h1>


        <div className={styles.grid}>
          <a href="/scan" className={styles.card}>
            <h2>Scan a qr code&rarr;</h2>
            <p>Scan a qr code with your camera</p>
          </a>

          <a href="/generate" className={styles.card}>
            <h2> Generate a qr code&rarr;</h2>
            <p> Generate a qr code with text or a link</p>
          </a>

          <Image height={200} id="badge">

          </Image>
        </div>
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
